### ISSUE TITLE
How to configure AWX for ILT playbooks

### ISSUE THREAD

**Issue by bmc1412** [IBM/ansible-automation-for-lmt#7]
Hello,

I am working with John Gardner and need to run playbook using AWX.
How to provide -i lmt_disconnected_scans_inventory.yml using AWX since it shows option for only select one playbook?

**Comment by arturobrzut** [comment]
Hi 
Please go with instruction 
https://github.com/IBM/ansible-automation-for-lmt
 
Using AWX or Tower to manage Disconnected Scanner
AWX is the open source, easy-to-use UI, dashboard and REST API for Ansible. Find out more about AWX here
Ansible Tower is a commercial version of AWX supported by Red Hat. Find out more about Tower here
1.  Install AWX or Tower.
2.  Create New Project with SCM TYPE as Git and provide URL to our repo.
3.  Create New Inventory. It needs the same structure as Inventory in repo: lmtserver, unix_endpoints group and endpoints inside this groups. Additionally, provide all required variables.
4.  Choose Credential type and define it.
5.  Create Job Template. Name it, provide inventory, credentials, project and then choose lmt_disconnected_scans_collector.yml as a playbook.
6. Schedule the job or lunch it manually.
ARTUR OBRZUT
Software Engineer
Phone: 48-12-628-9901
E-mail: artur.obrzut@pl.ibm.com
 
 
----- Oryginalna wiadomość -----Od: bmc1412 <notifications@github.com>Do: IBM/ansible-automation-for-lmt <ansible-automation-for-lmt@noreply.github.com>Dw: Subscribed <subscribed@noreply.github.com>Temat: [EXTERNAL] [IBM/ansible-automation-for-lmt] How to configure AWX for ILT playbooks (#7)Data: czw., 21 lis 2019 12:03 
Hello,
I am working with John Gardner and need to run playbook using AWX.How to provide -i lmt_disconnected_scans_inventory.yml using AWX since it shows option for only select one playbook?

**Comment by bmc1412** [comment]
Thanks Artur, able to run playbook
